name: "Publish release to Notion"
description: "Creates a new page in an existing database with release information"
inputs:
  token:
    description: "Notion API token"
    required: true
  database-id:
    description: "Notion database ID"
    required: true
  name-id:
    description: ""
    required: true
  version-id:
    description: ""
    required: true
  date-id:
    description: ""
    required: true
  base-download-url:
    description: ""
    required: false
  mac-notion-id:
    description: ""
    required: false
  mac-file-path:
    description: ""
    required: false
  win-notion-id:
    description: ""
    required: false
  win-file-path:
    description: ""
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
